site_name: 668专业可信赖

nav:
  - YH证券: 'yhsg.md'
  - ZS证券: 'zs.md'
  - CJ证券: 'cj.md'
  - YB证券: 'hb.md'
  - HX证券: 'hx.md'
  - GJ证券: 'gj.md'
  - HT证券: 'huatai.md'

site_description: 万一免五、券商开户、低佣券商开户、开户

site_author: "668"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/baidu_analytics.js

theme:
  name: mkdocs
  custom_dir: custom_theme/