site_name: 668专业可信赖

nav:
  - YH证券: 'yh.md'
  - ZS证券: 'zs.md'
  - YB证券: 'hb.md'
  - HX证券: 'hx.md'
  - GJ证券: 'gj.md'
  - HT证券: 'huatai.md'
  - 信用卡: 
    - 中信银行: 'xyk/zx.md'
    - 交通银行: 'xyk/jt.md'
    - 华夏银行: 'xyk/hx.md'
    - 招商银行: 'xyk/zs.md'
    - 浦发银行: 'xyk/pf.md'
    - 平安银行: 'xyk/pa.md'
    - 广发银行: 'xyk/gf.md'
    - 其他银行: 'xyk/qt.md'

site_description: 万一免五、券商开户、低佣券商开户、开户

site_author: "668"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/baidu_analytics.js

theme:
  name: mkdocs
  custom_dir: custom_theme/